services:
  web-va:
    build: ./web-va
    container_name: va-ollama
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - LLM_API_URL=http://ollama:11434/v1
    depends_on:
      - ollama
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-cntr
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ollama_models: